
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 30 01:02:06 IST 2011
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int LCBR = 23;
  public static final int LTE = 29;
  public static final int UMINUS = 49;
  public static final int INTEGER = 20;
  public static final int SEMI = 41;
  public static final int CONTINUE = 8;
  public static final int INT = 19;
  public static final int MINUS = 30;
  public static final int STATIC = 42;
  public static final int LT = 28;
  public static final int LP = 24;
  public static final int COMMA = 7;
  public static final int CLASS = 5;
  public static final int RP = 40;
  public static final int PLUS = 36;
  public static final int MULTIPLY = 32;
  public static final int QUOTE = 44;
  public static final int ASSIGN = 2;
  public static final int IF = 18;
  public static final int THIS = 45;
  public static final int DOT = 10;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 39;
  public static final int RCBR = 38;
  public static final int LB = 22;
  public static final int LAND = 21;
  public static final int EQUAL = 11;
  public static final int TRUE = 46;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int RB = 37;
  public static final int LOR = 27;
  public static final int NULL = 35;
  public static final int MOD = 31;
  public static final int BREAK = 4;
  public static final int VOID = 47;
  public static final int GTE = 16;
  public static final int ELSE = 13;
  public static final int WHILE = 48;
  public static final int NEQUAL = 33;
  public static final int CLASS_ID = 6;
  public static final int EXTENDS = 12;
  public static final int STRING = 43;
  public static final int LNEG = 26;
  public static final int FALSE = 14;
  public static final int GT = 15;
  public static final int LENGTH = 25;
}

